# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=8192']

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.6.0
  hooks:
    - id: markdownlint-cli2
      args: []
